# Assignment -3 

In [130]:
import numpy as np
import pandas as pd

In [131]:
df = pd.read_csv(r'E:\vitExternship\fifa_data.csv')

In [132]:
df.head()

Unnamed: 0      ID               Name  Age  \
0           0  158023           L. Messi   31   
1           1   20801  Cristiano Ronaldo   33   
2           2  190871          Neymar Jr   26   
3           3  193080             De Gea   27   
4           4  192985       K. De Bruyne   27   

                                            Photo Nationality  \
0  https://cdn.sofifa.org/players/4/19/158023.png   Argentina   
1   https://cdn.sofifa.org/players/4/19/20801.png    Portugal   
2  https://cdn.sofifa.org/players/4/19/190871.png      Brazil   
3  https://cdn.sofifa.org/players/4/19/193080.png       Spain   
4  https://cdn.sofifa.org/players/4/19/192985.png     Belgium   

                                  Flag  Overall  Potential  \
0  https://cdn.sofifa.org/flags/52.png       94         94   
1  https://cdn.sofifa.org/flags/38.png       94         94   
2  https://cdn.sofifa.org/flags/54.png       92         93   
3  https://cdn.sofifa.org/flags/45.png       91         93   
4   https://cdn.sofifa.org/flags/7.png       91         92   

                  Club  ... Composure Marking StandingTackle  SlidingTackle  \
0         FC Barcelona  ...      96.0    33.0           28.0           26.0   
1             Juventus  ...      95.0    28.0           31.0           23.0   
2  Paris Saint-Germain  ...      94.0    27.0           24.0           33.0   
3    Manchester United  ...      68.0    15.0           21.0           13.0   
4      Manchester City  ...      88.0    68.0           58.0           51.0   

  GKDiving  GKHandling  GKKicking  GKPositioning GKReflexes Release Clause  
0      6.0        11.0       15.0           14.0        8.0        €226.5M  
1      7.0        11.0       15.0           14.0       11.0        €127.1M  
2      9.0         9.0       15.0           15.0       11.0        €228.1M  
3     90.0        85.0       87.0           88.0       94.0        €138.6M  
4     15.0        13.0        5.0           10.0       13.0        €196.4M  

[5 rows x 89 columns]

In [133]:
df.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [134]:
df.shape

(18207, 89)

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 89 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                18207 non-null  int64  
 1   ID                        18207 non-null  int64  
 2   Name                      18207 non-null  object 
 3   Age                       18207 non-null  int64  
 4   Photo                     18207 non-null  object 
 5   Nationality               18207 non-null  object 
 6   Flag                      18207 non-null  object 
 7   Overall                   18207 non-null  int64  
 8   Potential                 18207 non-null  int64  
 9   Club                      17966 non-null  object 
 10  Club Logo                 18207 non-null  object 
 11  Value                     18207 non-null  object 
 12  Wage                      18207 non-null  object 
 13  Special                   18207 non-null  int64  
 14  Prefer

In [136]:
df.isnull().sum()

Unnamed: 0           0
ID                   0
Name                 0
Age                  0
Photo                0
                  ... 
GKHandling          48
GKKicking           48
GKPositioning       48
GKReflexes          48
Release Clause    1564
Length: 89, dtype: int64

In [137]:
# Removing Missing values
na = pd.notnull(df["Position"])
df = df[na]

In [138]:
df.isnull().sum()

Unnamed: 0           0
ID                   0
Name                 0
Age                  0
Photo                0
                  ... 
GKHandling           0
GKKicking            0
GKPositioning        0
GKReflexes           0
Release Clause    1504
Length: 89, dtype: int64

In [139]:
df.shape

(18147, 89)

In [140]:
# The above are all the required features which we need to take into
# consideration. The Position feature here is the Y value or target variable
# and the rests are input variables or X
df = df[["Position", 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes']]

# Categorical Positions

In [141]:
forward_player = ["ST", "LW", "RW", "LF", "RF", "RS","LS", "CF"]
midfielder_player = ["CM","RCM","LCM", "CDM","RDM","LDM", "CAM", "LAM", "RAM", "RM", "LM"]
defender_player = ["CB", "RCB", "LCB", "LWB", "RWB", "LB", "RB"]

# Label encoding

In [142]:
df.loc[df["Position"] == "GK", "Position"] = 0

df.loc[df["Position"].isin(defender_player), "Position"] = 1

df.loc[df["Position"].isin(midfielder_player), "Position"] = 2

df.loc[df["Position"].isin(forward_player), "Position"] = 3

In [148]:
x = df.drop("Position",axis=1)
x

Finishing  HeadingAccuracy  ShortPassing  Volleys  Dribbling  Curve  \
0           95.0             70.0          90.0     86.0       97.0   93.0   
1           94.0             89.0          81.0     87.0       88.0   81.0   
2           87.0             62.0          84.0     84.0       96.0   88.0   
3           13.0             21.0          50.0     13.0       18.0   21.0   
4           82.0             55.0          92.0     82.0       86.0   85.0   
...          ...              ...           ...      ...        ...    ...   
18202       38.0             40.0          49.0     25.0       42.0   30.0   
18203       52.0             52.0          43.0     36.0       39.0   32.0   
18204       40.0             46.0          38.0     38.0       45.0   38.0   
18205       50.0             39.0          42.0     40.0       51.0   34.0   
18206       34.0             46.0          48.0     30.0       43.0   40.0   

       FKAccuracy  LongPassing  BallControl  Acceleration  ...  Penalties  \
0            94.0         87.0         96.0          91.0  ...       75.0   
1            76.0         77.0         94.0          89.0  ...       85.0   
2            87.0         78.0         95.0          94.0  ...       81.0   
3            19.0         51.0         42.0          57.0  ...       40.0   
4            83.0         91.0         91.0          78.0  ...       79.0   
...           ...          ...          ...           ...  ...        ...   
18202        34.0         45.0         43.0          54.0  ...       43.0   
18203        20.0         25.0         40.0          41.0  ...       43.0   
18204        27.0         28.0         44.0          70.0  ...       55.0   
18205        32.0         32.0         52.0          61.0  ...       50.0   
18206        34.0         44.0         51.0          57.0  ...       33.0   

       Composure  Marking  StandingTackle  SlidingTackle  GKDiving  \
0           96.0     33.0            28.0           26.0       6.0   
1           95.0     28.0            31.0           23.0       7.0   
2           94.0     27.0            24.0           33.0       9.0   
3           68.0     15.0            21.0           13.0      90.0   
4           88.0     68.0            58.0           51.0      15.0   
...          ...      ...             ...            ...       ...   
18202       45.0     40.0            48.0           47.0      10.0   
18203       42.0     22.0            15.0           19.0      10.0   
18204       41.0     32.0            13.0           11.0       6.0   
18205       46.0     20.0            25.0           27.0      14.0   
18206       43.0     40.0            43.0           50.0      10.0   

       GKHandling  GKKicking  GKPositioning  GKReflexes  
0            11.0       15.0           14.0         8.0  
1            11.0       15.0           14.0        11.0  
2             9.0       15.0           15.0        11.0  
3            85.0       87.0           88.0        94.0  
4            13.0        5.0           10.0        13.0  
...           ...        ...            ...         ...  
18202        13.0        7.0            8.0         9.0  
18203         9.0        9.0            5.0        12.0  
18204         5.0       10.0            6.0        13.0  
18205         6.0       14.0            8.0         9.0  
18206        15.0        9.0           12.0         9.0  

[18147 rows x 33 columns]

In [149]:
y = df["Position"]

In [150]:
y

0        3
1        3
2        3
3        0
4        2
        ..
18202    2
18203    3
18204    3
18205    3
18206    2
Name: Position, Length: 18147, dtype: object

# Feature scaling

In [152]:
from sklearn.preprocessing import StandardScaler
from keras.utils import to_categorical
ss = StandardScaler()
x = pd.DataFrame(ss.fit_transform(x))
y = to_categorical(y)

# Test Train and Split

In [155]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x.values, y, test_size=0.2,random_state=0)

In [156]:
x_train.shape

(14517, 33)

In [157]:
y_train.shape

(14517, 4)

# Module Building
    1. Import Necessary Libraries
    2. Add input layer (inputs = no of inputs in dataset=n, weights=random,AF=relu)
    3. Add Hidden layer (No of hidden nodes=inputs=2n or n/2, weights=random,AF=relu)
    4. Add output layer(inputs, weights, AF
                       Regression-1, random, relu
                       Binary-1, random, sigmoid 
                       Categorial- no of classes, random, softmax)
    5. Configure the learning process
        (loss function, accuracy, optimizer)
       Regression - (MSE, Gradient/Stochastic/Mini Batch)
       Binary - (binary cross entropy, accuracy,  Gradient/Stochastic/Mini Batch )
       Categorical - (Categorical cross entropy, accuracy,  Gradient/Stochastic/Mini Batch )
    6. Fit the model (x_train, y_train, batch_size, no on epochs)

# Importing Libraries

In [158]:
import tensorflow as tf
import keras as ks

In [159]:
from keras.models import Sequential
from keras.layers import Dense

In [160]:
model = Sequential()

# Input Layer

In [161]:
model.add(Dense(units=20,kernel_initializer='random_uniform',activation='relu'))

# 1st Input Layer

In [162]:
model.add(Dense(units=5,kernel_initializer='random_uniform',activation='relu'))

# 2nd Input Layer

In [163]:
model.add(Dense(units=5,kernel_initializer='random_uniform',activation='relu'))

# Output Layer

In [164]:
model.add(Dense(units=4,kernel_initializer='random_uniform',activation='softmax'))

# Configure Learning Process

In [165]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

# Fit the model

In [167]:
model.fit(x_train,y_train,epochs=10,batch_size=30)

Epoch 1/10
484/484 [==============================] - 1s 1ms/step - loss: 0.6444 - accuracy: 0.7257
Epoch 2/10
484/484 [==============================] - 1s 1ms/step - loss: 0.5772 - accuracy: 0.7798
Epoch 3/10
484/484 [==============================] - 1s 1ms/step - loss: 0.5228 - accuracy: 0.8569
Epoch 4/10
484/484 [==============================] - 1s 1ms/step - loss: 0.4832 - accuracy: 0.8607
Epoch 5/10
484/484 [==============================] - 1s 1ms/step - loss: 0.4542 - accuracy: 0.8640
Epoch 6/10
484/484 [==============================] - 1s 1ms/step - loss: 0.4304 - accuracy: 0.8630
Epoch 7/10
484/484 [==============================] - 1s 1ms/step - loss: 0.4143 - accuracy: 0.8637
Epoch 8/10
484/484 [==============================] - 1s 1ms/step - loss: 0.3992 - accuracy: 0.8655
Epoch 9/10
484/484 [==============================] - 1s 1ms/step - loss: 0.3878 - accuracy: 0.8654
Epoch 10/10
484/484 [==============================] - 1s 1ms/step - loss: 0.3786 - accuracy: 0.8664

# Test the model

In [168]:
ypred = model.predict(x_test)

114/114 [==============================] - 0s 834us/step


In [169]:
ypred

array([[5.62837773e-35, 1.30346641e-01, 8.40376139e-01, 2.92771757e-02],
       [1.49563409e-03, 1.11233685e-02, 2.54319519e-01, 7.33061433e-01],
       [0.00000000e+00, 9.98305917e-01, 1.69410312e-03, 1.92440774e-17],
       ...,
       [1.51297253e-09, 2.46250816e-02, 4.39794242e-01, 5.35580695e-01],
       [4.63672230e-15, 4.30646576e-02, 6.14607871e-01, 3.42327535e-01],
       [0.00000000e+00, 8.49610567e-01, 1.50389388e-01, 1.87447764e-08]],
      dtype=float32)

In [170]:
y_test

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]], dtype=float32)

In [171]:
x_test[0]

array([-0.28423491, -1.05290129,  0.22486679,  0.00496078,  0.08591725,
        0.58838934,  0.1220833 ,  0.40970312,  0.21726894, -0.04104704,
       -0.11782076,  0.30461389, -1.09192728,  0.78069862, -0.20105535,
       -1.95322547, -0.32848504, -1.30006745,  0.04603806, -0.05044713,
       -0.42048637,  0.20674945,  0.32462554, -0.09847817, -0.0569325 ,
       -0.1148776 , -0.12472303, -0.07827814, -0.26086981, -0.25984435,
       -0.31708392, -0.49244979, -0.54084783])

In [172]:
y_test[0]

array([0., 0., 1., 0.], dtype=float32)

In [181]:
predict = model.predict([[-0.28423491, -1.05290129,  0.22486679,  0.00496078,  0.08591725,
        0.58838934,  0.1220833 ,  0.40970312,  0.21726894, -0.04104704,
       -0.11782076,  0.30461389, -1.09192728,  0.78069862, -0.20105535,
       -1.95322547, -0.32848504, -1.30006745,  0.04603806, -0.05044713,
       -0.42048637,  0.20674945,  0.32462554, -0.09847817, -0.0569325 ,
       -0.1148776 , -0.12472303, -0.07827814, -0.26086981, -0.25984435,
       -0.31708392, -0.49244979, -0.54084783]])

1/1 [==============================] - 0s 32ms/step


In [214]:
maxElem = np.argmax(predict,axis=1)
new_mat = np.zeros(predict.shape)
new_mat[0][maxElem]=1
new_mat

array([[0., 0., 1., 0.]])

# End of Assignment